#ifndef LV_CONF_H
#define LV_CONF_H
/* LVGL-only snapshot from the RootMaker ESP-IDF 5.5.4 default configuration.
 * Use LVGL's own Kconfig translator, as host/pixels does. No ESP32 drivers or
 * machine-local sdkconfig path are needed to rebuild this browser target. */
#define CONFIG_LV_CONF_SKIP 1
#define CONFIG_LV_CONF_MINIMAL 1
#define CONFIG_LV_COLOR_DEPTH_16 1
#define CONFIG_LV_COLOR_DEPTH 16
#define CONFIG_LV_USE_BUILTIN_MALLOC 1
#define CONFIG_LV_USE_BUILTIN_STRING 1
#define CONFIG_LV_USE_BUILTIN_SPRINTF 1
#define CONFIG_LV_MEM_SIZE_KILOBYTES 64
#define CONFIG_LV_MEM_POOL_EXPAND_SIZE_KILOBYTES 0
#define CONFIG_LV_MEM_ADR 0x0
#define CONFIG_LV_DEF_REFR_PERIOD 33
#define CONFIG_LV_DPI_DEF 130
#define CONFIG_LV_OS_NONE 1
#define CONFIG_LV_DRAW_BUF_STRIDE_ALIGN 1
#define CONFIG_LV_DRAW_BUF_ALIGN 4
#define CONFIG_LV_DRAW_LAYER_SIMPLE_BUF_SIZE 24576
#define CONFIG_LV_DRAW_LAYER_MAX_MEMORY 0
#define CONFIG_LV_USE_DRAW_SW 1
#define CONFIG_LV_DRAW_SW_SUPPORT_RGB565 1
#define CONFIG_LV_DRAW_SW_SUPPORT_RGB565_SWAPPED 1
#define CONFIG_LV_DRAW_SW_SUPPORT_RGB565A8 1
#define CONFIG_LV_DRAW_SW_SUPPORT_RGB888 1
#define CONFIG_LV_DRAW_SW_SUPPORT_XRGB8888 1
#define CONFIG_LV_DRAW_SW_SUPPORT_ARGB8888 1
#define CONFIG_LV_DRAW_SW_SUPPORT_ARGB8888_PREMULTIPLIED 1
#define CONFIG_LV_DRAW_SW_SUPPORT_L8 1
#define CONFIG_LV_DRAW_SW_SUPPORT_AL88 1
#define CONFIG_LV_DRAW_SW_SUPPORT_A8 1
#define CONFIG_LV_DRAW_SW_SUPPORT_I1 1
#define CONFIG_LV_DRAW_SW_I1_LUM_THRESHOLD 127
#define CONFIG_LV_DRAW_SW_DRAW_UNIT_CNT 1
#define CONFIG_LV_DRAW_SW_COMPLEX 1
#define CONFIG_LV_DRAW_SW_SHADOW_CACHE_SIZE 0
#define CONFIG_LV_DRAW_SW_CIRCLE_CACHE_SIZE 4
#define CONFIG_LV_DRAW_SW_ASM_NONE 1
#define CONFIG_LV_USE_DRAW_SW_ASM 0
#define CONFIG_LV_ASSERT_HANDLER_INCLUDE "assert.h"
#define CONFIG_LV_CACHE_DEF_SIZE 0
#define CONFIG_LV_IMAGE_HEADER_CACHE_DEF_CNT 0
#define CONFIG_LV_GRADIENT_MAX_STOPS 2
#define CONFIG_LV_COLOR_MIX_ROUND_OFS 128
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN_SIZE 1
#define CONFIG_LV_FONT_MONTSERRAT_16 1
#define CONFIG_LV_FONT_MONTSERRAT_24 1
#define CONFIG_LV_FONT_UNSCII_8 1
#define CONFIG_LV_FONT_DEFAULT_UNSCII_8 1
#define CONFIG_LV_USE_FONT_PLACEHOLDER 1
#define CONFIG_LV_TXT_ENC_UTF8 1
#define CONFIG_LV_TXT_BREAK_CHARS " ,.;:-_)}"
#define CONFIG_LV_TXT_LINE_BREAK_LONG_LEN 0
#define CONFIG_LV_TXT_COLOR_CMD "#"
#define CONFIG_LV_USE_IMAGE 1
#define CONFIG_LV_USE_LABEL 1
#define CONFIG_LV_LABEL_WAIT_CHAR_COUNT 3
#define CONFIG_LV_FS_DEFAULT_DRIVER_LETTER 0
#define CONFIG_LV_USE_SYSMON 1
#define CONFIG_LV_USE_PERF_MONITOR 1
#define CONFIG_LV_PERF_MONITOR_ALIGN_BOTTOM_RIGHT 1
#define CONFIG_LV_USE_OBSERVER 1
#define CONFIG_LVGL_VERSION_MAJOR 9
#define CONFIG_LVGL_VERSION_MINOR 5
#define CONFIG_LVGL_VERSION_PATCH 0
#include "src/lv_conf_kconfig.h"
#endif
